### PR TITLE
Remove confusing verbiage regarding patching fonts

### PR DESCRIPTION
**Pull request by Asuza**
This is a simple text change to make the sentence about manually-patching fonts to make more sense.

### CODE REVIEW

**Comment by gpakosz** [comment]
I'm sorry but I disagree with your suggestion.

Running the [font patching tool](https://github.com/powerline/fontpatcher) created by the folks behind Powerline is **no more documented** in the Powerline manual.

However **what's still documented** in the Powerline manual is installing pre-patched fonts from a [repository that hasn't been updated for years](https://github.com/powerline/fonts) (except 10 months ago to add a font). It also happens that ponts patched by others, on another system may not be the perfect fit your one's system so I still don't see it as a recommended way to benefit from Powerline symbols.

**Comment by Asuza** [comment]
Sorry, I misunderstood [the Linux-specific instructions](https://powerline.readthedocs.io/en/latest/installation/linux.html#patched-font-installation) and confused the manual installation instructions with manual patching instructions.

I was reading **no more documented** as if it might have had a typo in it. That's the part that threw me off, thinking **no** might be a typo of **now**.

Would you be okay with the following tweak? (bold is for emphasis on the change):

this is the most difficult way and is **no longer** documented in the Powerline manual

**Comment by gpakosz** [comment]
Either your suggestion + changing the end of the sentence a bit so that it doesn't link to the power line manual:
```
Powerline symbols: this is the most difficult way and is no more documented by the Powerline project
```

Or removing that option all together. What do you think is the way forward? It's been a while since I looked at the Powerline project

**Comment by Asuza** [comment]
I think dropping the line entirely makes sense. I may be speculating too much, but I imagine if someone really wants to patch their own fonts instead of using an easier method, they may have already done some research on it and already found the unmaintained tool.

**Comment by gpakosz** [comment]
Fair enough 👌

Can you please sync the commit message with the actual change btw?

**Comment by Asuza** [comment]
I updated my branch with the changes we discussed, updating the commit message. Let me know if it needs any further changes.

**Comment by gpakosz** [comment]
Thanks @Asuza 👍

**Pull request merged**
