### PR TITLE
Add variables for config path

### PR DESCRIPTION
**Pull request by rendler-denis**
Add variables to define .tmux.conf and .tmux.conf.local path

### CODE REVIEW

**Comment by gpakosz** [comment]
Hello @rendler-denis 👋

What is this PR for?

My understanding is that you're expecting `TMUX_CONF_PATH` and `TMUX_LOCAL_CONF_PATH` to be exported before tmux launches. But it seems to me you **also** need to launch tmux with `$ tmux -f "$TMUX_CONF_PATH"` right?

I'm afraid I can't see the value of all this 🤔

**Comment by rendler-denis** [comment]
hi. this is meant to add a bit of flexibility in the location where these files are stored. for example, I am using a ~/dotfiles folder where I store these. as far as I tested this does not add any BC breaks only offering these env vars as a supplement if needed.

**Comment by gpakosz** [comment]
But how do you launch tmux?

**Comment by rendler-denis** [comment]
either by running `$ tmux` or `TMUX_CONF_PATH=~/dotfile/tmux.conf  tmux`

**Comment by gpakosz** [comment]
Hello @rendler-denis 👋

I won't merge this PR as it's simply broken.
However, you're welcome if you want to experiment with the `gh216-gh221` branch that implements the feature.

Hope that helps! 🤞

**Pull request closed without merging**
