### PR TITLE
Extract shell script out of ~/.tmux.conf

### PR DESCRIPTION
**Pull request by Kidlike**
The main idea here was to extract the embedded shell script of tmux.conf out on it's own file.
This way the code is more maintainable and performs better.

This lead to the need of splitting tmux.local.conf to 2 files, a property file and a tmux conf file (because it's sourced from both tmux, and shell).

It should be now possible to split the shell script into smaller parts that can be used individually (a bit more performance optimization).

I also added an installed. I think it's good for many reasons (reproducible results, easier integration with dotbot, less readme)

Thanks for your initial idea, it's really awesome. I believe this PR will help the project to mature further.

_(NOTE-1: I haven't changed any of your configs, just moved them around)
(NOTE-2: I haven't updated the README)
(NOTE-3: Consider renaming your repo to `oh-my-tmux` :) )_

### CODE REVIEW

**Comment by gpakosz** [comment]
Hello @Kidlike,

It seems you put a lot of efforts in this PR and to honor that I'm going to review it.

But first, I believe you should contact maintainers before engaging into such major refactoring. A key value proposition of my configuration is being self contained: you just copy around `tmux.conf` and it just works. Splitting it into script and dependencies is how everybody else is doing it and I don't want to take that route. That sole perspective makes your PR rather moot.

> The main idea here was to extract the embedded shell script of tmux.conf out on it's own file.
> This way the code is more maintainable and performs better.
>

"more maintainable" is highly subjective and "performs better" is hypothetical.

> This lead to the need of splitting tmux.local.conf to 2 files, a property file and a tmux conf file (because it's sourced from both tmux, and shell).

I read it as "it makes things more complex".

> It should be now possible to split the shell script into smaller parts that can be used individually (a bit more performance optimization).

This is again hypothetical ihmo.

> I also added an installer. I think it's good for many reasons (reproducible results, easier integration with dotbot, less readme)

Small nitpicking first: I don't believe `.bsh` is an accepted convention for Bash scripts extension.
Then I prefer people realize what they're doing while following the 4 tiny install steps. They are optional anyways and as mentioned above copying around `tmux.conf` from machine to machine just works.

Having an install script also tends to make people believe they can `curl install.sh | bash` but your install script starts with some introspection to locate itself on the filesystem.

> Thanks for your initial idea, it's really awesome.

Thank you!

> I believe this PR will help the project to mature further.

I'm sorry but I personally believe it doesn't. I know you invested time in this but this is taking a direction I don't approve of.

> (NOTE-1: I haven't changed any of your configs, just moved them around)

From what I can see, that's not entirely true. You changed colors and attributes. You removed comments (e.g. the comments about Powerline which I ended up adding because too many people were confused about whether they should install some Powerline thing first).

---

All in all, I won't accept this pull request. Thank you for your understanding. I hope we're still friends.

**Comment by Kidlike** [comment]
*Monica, no feelings at all*.
I made these changes for me firstmost, and I will keep them on my fork (although that one contains more changes).

> more maintainable

Not subjective. Having a shell script behind a comment-wall, makes it difficult to read, difficult to write, syntax checkers to fail, highlighters to fail, etc...
Because you are used to editing this pile of entangled string doesn't mean it's maintainable; or that anyone else wants to.

> performs better

Not hypothetical. `cut -c3- larger-file | sh -s function` CANNOT perform better than `sh smaller-file function`. AND has the potential to become more optimized whereas right now that's an impossibility (it can only grow).

> tmux.local.conf split

Now this IS subjective. IMO it actually makes things more clear, the one is a property file that you set colors etc that are used by `oh-my-tmux`, and the other is just a `tmux` config file that has really no relation to this project - but some generic defaults. (probably the file naming should be better).

> install script

If you had ONLY 1 file, I could understand your argument, but you don't. You have 2, so it's not just "copy around" `tmux.conf`. This is a non-argument.

> Having an install script also tends to make people believe

That's just an assumption. People are doing both.

> NOTE-1

Nope, I haven't changed the content. Just removed the in-line comments. They could be added on next or previous lines if they are essential.

---

I know that when someone makes changes to your code is hard to accept it because you are attached to it; it's essentially an attack to your personality.
Because who we are if not stand by our opinions :)
I hope one day you will realize and learn.
Feel free to close this.
No hard feelings, I made these changes for me firstmost, and I will keep them on my fork (although that contains more changes).

> more maintainable

Not subjective. Having a shell script behind a comment-wall, makes it difficult to read, difficult to write, syntax checkers to fail, highlighters to fail, etc...
Because YOU are used to editing this pile of entangled string doesn't mean it's maintainable; or that anyone else wants to.
Ever wondered why you are the only contributor to this project, even though it has so many stars and forks?

> performs better

Not hypothetical. `cut -c3- larger-file | sh -s function` CANNOT perform better than `sh smaller-file function`. AND has the potential to become more optimized whereas right now that's an impossibility (it can only grow).

> tmux.local.conf split

Now this IS subjective. IMO it actually makes things more clear, the one is a property file that you set colors etc that are used by `oh-my-tmux`, and the other is just a `tmux` config file that has really no relation to this project - but some generic defaults. (probably the file naming should be better).

> install script

If you had ONLY 1 file, I could understand your argument, but you don't. You have 2, so it's not just "copy around" `tmux.conf`. This is a non-argument.

> Having an install script also tends to make people believe

That's just an assumption. People are doing both.

> NOTE-1

Nope, I haven't changed the content. Just removed the in-line comments. They could be added on next or previous lines if they are essential.

---

I know that when someone makes changes to your code is hard to accept it because you are attached to it; it's essentially an attack to your personality.
Because who we are if not stand by our opinions :)

But this is not how open source works.

Have you realized how bad your project is that it has so many stars and forks and only 1 contributor and 1 accepted PR ?

I hope one day you will realize and learn.
Feel free to close this.

**Comment by gpakosz** [comment]
> Not subjective. Having a shell script behind a comment-wall, makes it difficult to read, difficult to write, syntax checkers to fail, highlighters to fail, etc...

It indeed depends on what I'm used to. That being said `cut -c3- ~/.tmux.conf | shellcheck -s sh` works just fine.

Also while developing. You're not obliged to do it in `tmux.conf` directly.

> Not hypothetical. `cut -c3- larger-file | sh -s function` CANNOT perform better than `sh smaller-file function`. AND has the potential to become more optimized whereas right now that's an impossibility (it can only grow).

If `cut -c3- larger-file | sh -s function` becomes unbearably slow, it's a clear indication it's time to stop piling up stuff. I don't believe I've reached that point. I reckon that's also subjective.

> Have you realized how bad your project is that it has so many stars and forks and only 1 contributor and 1 accepted PR ?
>
> I hope one day you will realize and learn.

Now you're being rude.

**Comment by Kidlike** [comment]
Truth hurts :)

Anyway, have a good one.

**Pull request closed without merging**
