### PR TITLE
added load average

### PR DESCRIPTION
**Pull request by ytang**
Hello,

I added a new variable, `loadavg`, that shows the load average of the last minute. I didn't add the OpenBSD branch because I only have Mac and Linux. If you find it useful, please consider merging. Thanks!

Cheers,
Yang

### CODE REVIEW

**Comment by gpakosz** [comment]
Hello Yang,

I'm not a fan of adding `#{loadavg}` to the default `tmux_conf_theme_status_left`. I created the `loadavg` branch that includes most of your work and adds support for OpenBSD.

For the record, testing with OpenBSD is rather easy with `vagrant`:
```
$ vagrant init trombik/ansible-openbsd-6.0-amd64; vagrant up --provider virtualbox
$ vagrant ssh
$ export LANG=en_US.UTF-8
$ tmux
```

**Comment by ytang** [comment]
Thanks! Is it possible to merge `.tmux.conf` to master but leave `.tmux.conf.local` alone? Then I can just change my local configuration myself.

**Comment by gpakosz** [comment]
It seems I've been able to commit in your own name 😉

**Comment by ytang** [comment]
Great! Thanks a lot!

**Pull request merged**
