### PR TITLE
bugfix 1.9a maximize current pane

### PR DESCRIPTION
**Pull request by hanxi**
bugfix 1.9a maximize current pane

### CODE REVIEW

**Comment by gpakosz** [comment]
I won't accept this pull request.

The `.tmux.conf.local` file in the repository is meant to be an example file. Each user is supposed to create its own `~/.tmux.conf.local` and add its own settings. This is not the place to fix a broken feature. However, if you really decide you prefer stock's maximize pane feature (`resize-pane -Z`) instead of my enhanced maximize pane feature then yes you're totally entitled to add `bind + resize-pane -Z` to your own `~/.tmux.conf.local`

I can only make guesses about what made you open this pull request in the first place: I believe you're running the official tmux 1.9a which crashes when using the `swap-pane` command (as noted at the beginning of `README.md`). In that case, yes `<prefix>+` won't maximize the current pane and will warn you about your buggy tmux. From there, if you still want to use my enhanced maximize pane feature, your best bet is to compile tmux from source:

  - I gave an example here on [how to compile tmux for Linux](https://github.com/gpakosz/.tmux/issues/5#issuecomment-87792080)
  - for Mac, it's as easy as `brew uninstall tmux; brew install --HEAD tmux`

For those coming directly to this pull request through a Google search: the enhanced maximize pane feature scripted by this `.tmux.conf` allows you to further splits maximized panes into sub panes and at any time minimize back the maximized pane to its original place / window. In comparison, stock maximize pane (`resize-pane -Z`) exhibits a temporary nature.

Finally, I'll think about your idea of "degrading" to stock maximize pane (`resize-pane -Z`) in case I detect a buggy tmux 1.9a. But the fix would totally happen in implementation of the `maximize_pane` script that's inside `.tmux.conf`.

Cheers!

**Comment by hanxi** [comment]
I see. You are right.

How to close this pull request?

Thanks.

**Comment by gpakosz** [comment]
I'll leave it open for a while as it sheds some light on the enhanced maximize pane feature.

Out of curiosity, did you bother compiling tmux from source or installing it with `brew install --HEAD tmux` since reading my reply?

**Comment by hanxi** [comment]
I tried it in Mac. It's same to this:

**Comment by gpakosz** [comment]
Then yes if you prefer the builtin maximize pane feature (`resize-pane -Z`) the way to go is to add `bind + resize-pane -Z` in your `~/.tmux.conf.local`

**Comment by hanxi** [comment]
I think if the commond (`resize-pane -Z`) can change the name of pane will be better.
If status is maximize, so add a suffix to the pane's name.

**Pull request closed without merging**
